src/apps/customer/urls.py
# > Django
from django.urls import path
# > Vues
from customer.views import (
    ProfileUpdateView,
)


app_name = 'customer'
urlpatterns = [
    # > Profil
    path('profile/', ProfileUpdateView.as_view(), name='account_profile'),
]

src/myhvacrguide/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('myhvacrguidedieu/', admin.site.urls),
    # > Apps
    # core
    path("", include('core.urls')),
    # > Django-allauth
    path('accounts/', include('allauth.urls')),
    # > customer
    path('accounts/', include('customer.urls')),
]


###############################################################################
# > Barre de debug

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/templates/Aaatemplates/app/snippets/footer.html
{% load i18n %}
<footer class="footer-app mt-5 py-3 w-100">
  <hr class="divider bg-light">
  <div
    class="d-flex flex-row-reverse flex-lg-row flex-wrap flex-lg-nowrap justify-content-center justify-content-lg-between align-items-center pt-6 pb-2 mt-6">
    {# Liste gauche #}
    {# ---------------------------------------------- #}
    <ul
      class="list-unstyled d-flex flex-wrap col-12 col-lg-5 justify-content-center justify-content-lg-start mb-2 mb-lg-0">
      <li class="mr-3 mr-lg-0">
        <small class="font-weight-normal"><a href="terms-of-services.html"
            class="text-reset">{% trans "conditions d'utilisation" %}</a></small>
      </li>
    </ul>
    {# Icone centre #}
    {# ---------------------------------------------- #}
    <i class="far fa-snowflake d-none d-lg-block mx-lg-4"></i>
    {# Liste droite #}
    {# ---------------------------------------------- #}
    <ul
      class="list-unstyled d-flex flex-wrap col-12 col-lg-5 justify-content-center justify-content-lg-end mb-2 mb-lg-0">
      <li class="mr-3 mr-lg-0">
        <small class="font-weight-normal"><a href="terms-of-services.html"
            class="text-reset">{% trans "conditions d'utilisation" %}</a></small>
      </li>
    </ul>
  </div>
</footer>

src/templates/Aaatemplates/app/snippets/messages.html
{% for message in messages %}
  <div class="alert alert-dismissible {{ message.tags }} m-0" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      <div class="container-fluid">
        {{ message }}
      </div>
  </div>
{% endfor %}

src/templates/Aaatemplates/app/snippets/sidebar.html
{% load i18n %}

{% url 'customer:account_profile' as account_profile %}

{% url 'account_change_password' as account_change_password %}
{% url 'account_email' as account_email %}


{# sidebar #}
{# ---------------------------------------------- #}
<div class="sidebar-sticky pt-3">
  <ul class="sidebar-nav flex-column">
    <li class="{% if 'accounts/profile' in request.path %}nav-item active {% else %}nav-item {% endif %}">
      <a class="nav-link"
        href="{{ account_profile }}">
        <i class="fas fa-pencil-alt"></i>
        {% trans "Profil" %}
      </a>
    </li>
    <li class="{% if 'accounts/password/change' in request.path %}nav-item active {% else %}nav-item {% endif %}">
      <a class="nav-link"
        href="{{ account_change_password }}">
        <i class="fas fa-key"></i>
        {% trans "Sécurité" %}
      </a>
    </li>
    <li class="{% if 'accounts/email/' in request.path %}nav-item active {% else %}nav-item {% endif %}">
      <a class="nav-link"
        href="{{ account_email }}">
        <i class="fas fa-envelope"></i>
        {% trans "E-mails" %}
      </a>
    </li>
  </ul>
</div>